import { registerBlock } from '../registry';
import type { BlockDefinition } from '@/lib/types';

const heroBlock: BlockDefinition = {
  type: 'hero',
  label: 'Hero',
  description: 'Sezione hero con titolo, sottotitolo, sfondo parallax, video e CTA',
  icon: 'Layers',
  category: 'editorial',
  defaultProps: {
    templateId: 'hero-editorial-impact',
    title: 'Titolo Principale',
    subtitle: 'Sottotitolo di supporto',
    ctaText: 'Scopri di più',
    ctaUrl: '#',
    ctaStyle: 'primary',
    ctaPaddingX: 22,
    ctaPaddingY: 12,
    ctaRadius: 14,
    ctaFullWidth: false,
    ctaOffsetX: 0,
    ctaOffsetY: 0,
    ctaBgColor: '',
    ctaTextColor: '',
    ctaBorderColor: '',
    contentPaddingX: 32,
    contentPaddingY: 32,
    contentGap: 16,
    eyebrowBgColor: '',
    eyebrowTextColor: '',
    titleTag: 'h1',
    alignment: 'center',
    textAlign: 'center',
    contentPosition: 'center',
    contentWidth: '800px',
    contentOffsetX: 0,
    contentOffsetY: 0,
    panelStyle: 'none',
    eyebrow: '',
    height: '60vh',
    overlayOpacity: 0.5,
    overlayColor: '#000000',
    videoUrl: '',
    videoAutoplay: true,
    videoLoop: true,
    videoMuted: true,
  },
  defaultStyle: {
    layout: {
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
      padding: { top: '120px', right: '48px', bottom: '120px', left: '48px' },
      margin: { top: '0', right: '0', bottom: '0', left: '0' },
      width: '100%',
      maxWidth: '100%',
      minHeight: '600px',
    },
    background: {
      type: 'color',
      value: '#1a1a2e',
    },
    typography: {
      color: '#ffffff',
      textAlign: 'center',
    },
  },
  supportsChildren: false,
};

registerBlock(heroBlock);
