export interface NavigationTemplate {
  id: string;
  name: string;
  category: string;
  description: string;
  preview: string; // CSS color for preview
  defaultProps: Record<string, unknown>;
  defaultStyle: Record<string, unknown>;
}

const DEFAULT_NAV_ITEMS = [
  { id: '1', label: 'Home', url: '/', icon: 'home', children: [] },
  { id: '2', label: 'Chi Siamo', url: '/chi-siamo', icon: 'user', children: [] },
  { id: '3', label: 'Servizi', url: '/servizi', icon: 'layers', children: [] },
  { id: '4', label: 'Contatti', url: '/contatti', icon: 'phone', children: [] },
];

export const NAVIGATION_TEMPLATES: NavigationTemplate[] = [
  // ================== MINIMAL LINES (Linee semplici) ==================
  {
    id: 'minimal-underline',
    name: 'Minimal Underline',
    category: 'Minimal',
    description: 'Linea sottile sotto i link',
    preview: '#f3f4f6',
    defaultProps: {
      mode: 'custom',
      layout: 'horizontal',
      variant: 'underline',
      buttonShape: 'square',
      buttonPaddingX: 0,
      buttonPaddingY: 0,
      buttonRadius: 0,
      itemGap: 32,
      compact: false,
      showIcons: false,
      showBadges: true,
      sticky: true,
      placement: 'top',
      justify: 'space-between',
      items: DEFAULT_NAV_ITEMS,
    },
    defaultStyle: {
      layout: { padding: { top: 16, right: 24, bottom: 16, left: 24 } },
      background: { type: 'color', value: '#ffffff' },
    },
  },
  {
    id: 'minimal-separator',
    name: 'Minimal Separator',
    category: 'Minimal',
    description: 'Semplice linea tra item',
    preview: '#e5e7eb',
    defaultProps: {
      mode: 'custom',
      layout: 'horizontal',
      variant: 'inline',
      buttonShape: 'square',
      buttonPaddingX: 12,
      buttonPaddingY: 0,
      buttonRadius: 0,
      itemGap: 24,
      compact: false,
      showIcons: false,
      showBadges: true,
      sticky: true,
      placement: 'top',
      justify: 'space-between',
      items: DEFAULT_NAV_ITEMS,
    },
    defaultStyle: {
      layout: { padding: { top: 12, right: 24, bottom: 12, left: 24 } },
      background: { type: 'color', value: '#ffffff' },
    },
  },
  {
    id: 'minimal-spaced',
    name: 'Minimal Spaced',
    category: 'Minimal',
    description: 'Semplice con spacing',
    preview: '#f9fafb',
    defaultProps: {
      mode: 'custom',
      layout: 'horizontal',
      variant: 'inline',
      buttonShape: 'square',
      buttonPaddingX: 8,
      buttonPaddingY: 4,
      buttonRadius: 0,
      itemGap: 40,
      compact: false,
      showIcons: false,
      showBadges: true,
      sticky: true,
      placement: 'top',
      justify: 'space-between',
      items: DEFAULT_NAV_ITEMS,
    },
    defaultStyle: {
      layout: { padding: { top: 16, right: 24, bottom: 16, left: 24 } },
      background: { type: 'color', value: '#ffffff' },
    },
  },

  // ================== BUTTON STYLE (Pulsanti lisci) ==================
  {
    id: 'button-rect',
    name: 'Rectangular Buttons',
    category: 'Buttons',
    description: 'Pulsanti rettangolari lisci',
    preview: '#dbeafe',
    defaultProps: {
      mode: 'custom',
      layout: 'horizontal',
      variant: 'inline',
      buttonShape: 'square',
      buttonPaddingX: 14,
      buttonPaddingY: 8,
      buttonRadius: 2,
      itemGap: 8,
      compact: false,
      showIcons: false,
      showBadges: true,
      sticky: true,
      placement: 'top',
      justify: 'space-between',
      items: DEFAULT_NAV_ITEMS,
    },
    defaultStyle: {
      layout: { padding: { top: 12, right: 20, bottom: 12, left: 20 } },
      background: { type: 'color', value: '#ffffff' },
    },
  },
  {
    id: 'button-outlined',
    name: 'Outlined Buttons',
    category: 'Buttons',
    description: 'Pulsanti con bordo',
    preview: '#e0e7ff',
    defaultProps: {
      mode: 'custom',
      layout: 'horizontal',
      variant: 'inline',
      buttonShape: 'square',
      buttonPaddingX: 16,
      buttonPaddingY: 10,
      buttonRadius: 0,
      itemGap: 12,
      compact: false,
      showIcons: false,
      showBadges: true,
      sticky: true,
      placement: 'top',
      justify: 'space-between',
      items: DEFAULT_NAV_ITEMS,
    },
    defaultStyle: {
      layout: { padding: { top: 14, right: 24, bottom: 14, left: 24 } },
      background: { type: 'color', value: '#ffffff' },
    },
  },
  {
    id: 'button-filled',
    name: 'Filled Buttons',
    category: 'Buttons',
    description: 'Pulsanti riempiti',
    preview: '#bfdbfe',
    defaultProps: {
      mode: 'custom',
      layout: 'horizontal',
      variant: 'inline',
      buttonShape: 'square',
      buttonPaddingX: 16,
      buttonPaddingY: 10,
      buttonRadius: 2,
      itemGap: 10,
      compact: false,
      showIcons: false,
      showBadges: true,
      sticky: true,
      placement: 'top',
      justify: 'space-between',
      items: DEFAULT_NAV_ITEMS,
    },
    defaultStyle: {
      layout: { padding: { top: 16, right: 20, bottom: 16, left: 20 } },
      background: { type: 'color', value: '#ffffff' },
    },
  },
  {
    id: 'button-ghost',
    name: 'Ghost Buttons',
    category: 'Buttons',
    description: 'Pulsanti trasparenti',
    preview: '#f0f9ff',
    defaultProps: {
      mode: 'custom',
      layout: 'horizontal',
      variant: 'inline',
      buttonShape: 'square',
      buttonPaddingX: 12,
      buttonPaddingY: 8,
      buttonRadius: 2,
      itemGap: 24,
      compact: false,
      showIcons: false,
      showBadges: true,
      sticky: true,
      placement: 'top',
      justify: 'space-between',
      items: DEFAULT_NAV_ITEMS,
    },
    defaultStyle: {
      layout: { padding: { top: 12, right: 24, bottom: 12, left: 24 } },
      background: { type: 'color', value: '#ffffff' },
    },
  },
  {
    id: 'button-compact',
    name: 'Compact Buttons',
    category: 'Buttons',
    description: 'Pulsanti compatti',
    preview: '#e0f2fe',
    defaultProps: {
      mode: 'custom',
      layout: 'horizontal',
      variant: 'inline',
      buttonShape: 'square',
      buttonPaddingX: 10,
      buttonPaddingY: 6,
      buttonRadius: 0,
      itemGap: 6,
      compact: true,
      showIcons: false,
      showBadges: true,
      sticky: true,
      placement: 'top',
      justify: 'space-between',
      items: DEFAULT_NAV_ITEMS,
    },
    defaultStyle: {
      layout: { padding: { top: 8, right: 16, bottom: 8, left: 16 } },
      background: { type: 'color', value: '#ffffff' },
    },
  },

  // ================== BLOCK STYLE (Stile blocco) ==================
  {
    id: 'block-default',
    name: 'Block Default',
    category: 'Block',
    description: 'Blocchi standard',
    preview: '#f3f4f6',
    defaultProps: {
      mode: 'custom',
      layout: 'horizontal',
      variant: 'inline',
      buttonShape: 'square',
      buttonPaddingX: 16,
      buttonPaddingY: 12,
      buttonRadius: 0,
      itemGap: 8,
      compact: false,
      showIcons: false,
      showBadges: true,
      sticky: true,
      placement: 'top',
      justify: 'space-between',
      items: DEFAULT_NAV_ITEMS,
    },
    defaultStyle: {
      layout: { padding: { top: 20, right: 24, bottom: 20, left: 24 } },
      background: { type: 'color', value: '#ffffff' },
    },
  },
  {
    id: 'block-dark',
    name: 'Block Dark',
    category: 'Block',
    description: 'Blocchi su sfondo scuro',
    preview: '#1f2937',
    defaultProps: {
      mode: 'custom',
      layout: 'horizontal',
      variant: 'inline',
      buttonShape: 'square',
      buttonPaddingX: 16,
      buttonPaddingY: 12,
      buttonRadius: 0,
      itemGap: 8,
      compact: false,
      showIcons: false,
      showBadges: true,
      sticky: true,
      placement: 'top',
      justify: 'space-between',
      items: DEFAULT_NAV_ITEMS,
    },
    defaultStyle: {
      layout: { padding: { top: 20, right: 24, bottom: 20, left: 24 } },
      background: { type: 'color', value: '#1f2937' },
    },
  },
  {
    id: 'block-spaced',
    name: 'Block Spaced',
    category: 'Block',
    description: 'Blocchi spaziati',
    preview: '#e5e7eb',
    defaultProps: {
      mode: 'custom',
      layout: 'horizontal',
      variant: 'inline',
      buttonShape: 'square',
      buttonPaddingX: 18,
      buttonPaddingY: 14,
      buttonRadius: 0,
      itemGap: 16,
      compact: false,
      showIcons: false,
      showBadges: true,
      sticky: true,
      placement: 'top',
      justify: 'space-between',
      items: DEFAULT_NAV_ITEMS,
    },
    defaultStyle: {
      layout: { padding: { top: 24, right: 32, bottom: 24, left: 32 } },
      background: { type: 'color', value: '#ffffff' },
    },
  },

  // ================== TAB STYLE (Schede) ==================
  {
    id: 'tab-simple',
    name: 'Tab Simple',
    category: 'Tabs',
    description: 'Schede minimaliste',
    preview: '#f9fafb',
    defaultProps: {
      mode: 'custom',
      layout: 'horizontal',
      variant: 'underline',
      buttonShape: 'square',
      buttonPaddingX: 12,
      buttonPaddingY: 10,
      buttonRadius: 0,
      itemGap: 0,
      compact: false,
      showIcons: false,
      showBadges: true,
      sticky: true,
      placement: 'top',
      justify: 'flex-start',
      items: DEFAULT_NAV_ITEMS,
    },
    defaultStyle: {
      layout: { padding: { top: 0, right: 0, bottom: 0, left: 0 } },
      background: { type: 'color', value: '#ffffff' },
    },
  },
  {
    id: 'tab-boxed',
    name: 'Tab Boxed',
    category: 'Tabs',
    description: 'Schede con background',
    preview: '#f3f4f6',
    defaultProps: {
      mode: 'custom',
      layout: 'horizontal',
      variant: 'inline',
      buttonShape: 'square',
      buttonPaddingX: 14,
      buttonPaddingY: 8,
      buttonRadius: 0,
      itemGap: 4,
      compact: false,
      showIcons: false,
      showBadges: true,
      sticky: true,
      placement: 'top',
      justify: 'flex-start',
      items: DEFAULT_NAV_ITEMS,
    },
    defaultStyle: {
      layout: { padding: { top: 8, right: 12, bottom: 8, left: 12 } },
      background: { type: 'color', value: '#f9fafb' },
    },
  },
  {
    id: 'tab-filled',
    name: 'Tab Filled',
    category: 'Tabs',
    description: 'Schede piene',
    preview: '#dbeafe',
    defaultProps: {
      mode: 'custom',
      layout: 'horizontal',
      variant: 'inline',
      buttonShape: 'square',
      buttonPaddingX: 16,
      buttonPaddingY: 10,
      buttonRadius: 0,
      itemGap: 0,
      compact: false,
      showIcons: false,
      showBadges: true,
      sticky: true,
      placement: 'top',
      justify: 'flex-start',
      items: DEFAULT_NAV_ITEMS,
    },
    defaultStyle: {
      layout: { padding: { top: 0, right: 0, bottom: 0, left: 0 } },
      background: { type: 'color', value: '#ffffff' },
    },
  },

  // ================== MENU LAYOUTS (Menu) ==================
  {
    id: 'menu-spread',
    name: 'Menu Spread',
    category: 'Menu',
    description: 'Menu distribuito',
    preview: '#ffffff',
    defaultProps: {
      mode: 'custom',
      layout: 'horizontal',
      variant: 'inline',
      buttonShape: 'square',
      buttonPaddingX: 12,
      buttonPaddingY: 8,
      buttonRadius: 0,
      itemGap: 0,
      compact: false,
      showIcons: false,
      showBadges: true,
      sticky: true,
      placement: 'top',
      justify: 'space-around',
      items: DEFAULT_NAV_ITEMS,
    },
    defaultStyle: {
      layout: { padding: { top: 16, right: 0, bottom: 16, left: 0 } },
      background: { type: 'color', value: '#ffffff' },
    },
  },
  {
    id: 'menu-between',
    name: 'Menu Between',
    category: 'Menu',
    description: 'Menu spazi tra estremi',
    preview: '#f9fafb',
    defaultProps: {
      mode: 'custom',
      layout: 'horizontal',
      variant: 'inline',
      buttonShape: 'square',
      buttonPaddingX: 14,
      buttonPaddingY: 10,
      buttonRadius: 0,
      itemGap: 32,
      compact: false,
      showIcons: false,
      showBadges: true,
      sticky: true,
      placement: 'top',
      justify: 'space-between',
      items: DEFAULT_NAV_ITEMS,
    },
    defaultStyle: {
      layout: { padding: { top: 12, right: 24, bottom: 12, left: 24 } },
      background: { type: 'color', value: '#ffffff' },
    },
  },
  {
    id: 'menu-start',
    name: 'Menu Start',
    category: 'Menu',
    description: 'Menu allineato a sinistra',
    preview: '#f3f4f6',
    defaultProps: {
      mode: 'custom',
      layout: 'horizontal',
      variant: 'inline',
      buttonShape: 'square',
      buttonPaddingX: 12,
      buttonPaddingY: 8,
      buttonRadius: 0,
      itemGap: 24,
      compact: false,
      showIcons: false,
      showBadges: true,
      sticky: true,
      placement: 'top',
      justify: 'flex-start',
      items: DEFAULT_NAV_ITEMS,
    },
    defaultStyle: {
      layout: { padding: { top: 14, right: 24, bottom: 14, left: 24 } },
      background: { type: 'color', value: '#ffffff' },
    },
  },

  // ================== PILLS (Pillole) ==================
  {
    id: 'pills-light',
    name: 'Pills Light',
    category: 'Pills',
    description: 'Pillole leggere',
    preview: '#f0f9ff',
    defaultProps: {
      mode: 'custom',
      layout: 'horizontal',
      variant: 'pills',
      buttonShape: 'square',
      buttonPaddingX: 14,
      buttonPaddingY: 8,
      buttonRadius: 2,
      itemGap: 8,
      compact: false,
      showIcons: false,
      showBadges: true,
      sticky: true,
      placement: 'top',
      justify: 'space-between',
      items: DEFAULT_NAV_ITEMS,
    },
    defaultStyle: {
      layout: { padding: { top: 12, right: 16, bottom: 12, left: 16 } },
      background: { type: 'color', value: '#ffffff' },
    },
  },
  {
    id: 'pills-solid',
    name: 'Pills Solid',
    category: 'Pills',
    description: 'Pillole piene',
    preview: '#bfdbfe',
    defaultProps: {
      mode: 'custom',
      layout: 'horizontal',
      variant: 'inline',
      buttonShape: 'square',
      buttonPaddingX: 16,
      buttonPaddingY: 10,
      buttonRadius: 2,
      itemGap: 8,
      compact: false,
      showIcons: false,
      showBadges: true,
      sticky: true,
      placement: 'top',
      justify: 'space-between',
      items: DEFAULT_NAV_ITEMS,
    },
    defaultStyle: {
      layout: { padding: { top: 14, right: 18, bottom: 14, left: 18 } },
      background: { type: 'color', value: '#ffffff' },
    },
  },

  // ================== MODERN (Moderno) ==================
  {
    id: 'modern-clean',
    name: 'Modern Clean',
    category: 'Modern',
    description: 'Design pulito',
    preview: '#f8fafc',
    defaultProps: {
      mode: 'custom',
      layout: 'horizontal',
      variant: 'inline',
      buttonShape: 'square',
      buttonPaddingX: 16,
      buttonPaddingY: 12,
      buttonRadius: 2,
      itemGap: 12,
      compact: false,
      showIcons: false,
      showBadges: true,
      sticky: true,
      placement: 'top',
      justify: 'space-between',
      items: DEFAULT_NAV_ITEMS,
    },
    defaultStyle: {
      layout: { padding: { top: 16, right: 32, bottom: 16, left: 32 } },
      background: { type: 'color', value: '#ffffff' },
    },
  },
  {
    id: 'modern-bold',
    name: 'Modern Bold',
    category: 'Modern',
    description: 'Design audace',
    preview: '#e0e7ff',
    defaultProps: {
      mode: 'custom',
      layout: 'horizontal',
      variant: 'inline',
      buttonShape: 'square',
      buttonPaddingX: 20,
      buttonPaddingY: 14,
      buttonRadius: 2,
      itemGap: 8,
      compact: false,
      showIcons: true,
      showBadges: true,
      sticky: true,
      placement: 'top',
      justify: 'space-between',
      items: DEFAULT_NAV_ITEMS,
    },
    defaultStyle: {
      layout: { padding: { top: 20, right: 32, bottom: 20, left: 32 } },
      background: { type: 'color', value: '#ffffff' },
    },
  },
  {
    id: 'modern-minimal',
    name: 'Modern Minimal',
    category: 'Modern',
    description: 'Minimalista',
    preview: '#f9fafb',
    defaultProps: {
      mode: 'custom',
      layout: 'horizontal',
      variant: 'inline',
      buttonShape: 'square',
      buttonPaddingX: 8,
      buttonPaddingY: 6,
      buttonRadius: 0,
      itemGap: 32,
      compact: true,
      showIcons: false,
      showBadges: true,
      sticky: true,
      placement: 'top',
      justify: 'space-between',
      items: DEFAULT_NAV_ITEMS,
    },
    defaultStyle: {
      layout: { padding: { top: 12, right: 24, bottom: 12, left: 24 } },
      background: { type: 'color', value: '#ffffff' },
    },
  },
];

export function getNavigationTemplates(): NavigationTemplate[] {
  return NAVIGATION_TEMPLATES;
}

export function getNavigationTemplate(id: string): NavigationTemplate | undefined {
  return NAVIGATION_TEMPLATES.find(t => t.id === id);
}

export function getNavigationTemplatesByCategory(category: string): NavigationTemplate[] {
  return NAVIGATION_TEMPLATES.filter(t => t.category === category);
}
